import type { Metadata } from "next";
import "./globals.css";
import { Header } from "@/components/header"


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
  keywords: ['HTML', 'CSS', 'JavaScript', 'Programação'],
  openGraph: {
    images: ['https://avatars.githubusercontent.com/u/112730223?v=4']
  },
  robots:{
    index: true,
    follow: true,
    nocache: true,
    googleBot: {
      index: true,
      follow: true,
      noimageindex: true,
    }
  }
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body >
        <Header/>

        {children}
        </body>
    </html>
  );
}
